CREATE TABLE CLIENTE (
    IDCLI integer  NOT NULL,
    NOMCLIE varchar2(50)  NOT NULL,
    APECLIE varchar2(50)  NOT NULL,
    DOCCLIE char(8)  NOT NULL,
    EMACLIE varchar2(50)  NOT NULL,
    CELCLIE char(9)  NOT NULL,
    ESTCLIE char(1)  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (IDCLI)
) ;

CREATE TABLE EMPLEADO (
    IDEMP integer  NOT NULL,
    NOMEMP varchar2(50)  NOT NULL,
    APEEMP varchar2(50)  NOT NULL,
    EMAILEMP varchar2(50)  NOT NULL,
    CELEMP char(9)  NOT NULL,
    FEHCREGEMP date  NOT NULL,
    DOCEMP char(12)  NOT NULL,
    ESTEMP char(1)  NOT NULL,
    USUEMP varchar2(50) not null,
    PASEMP varchar2(50) NOT NULL,
    CONSTRAINT EMPLEADO_pk PRIMARY KEY (IDEMP)
) ;

CREATE TABLE MOTOS (
    IDMOT integer  NOT NULL,
    CATMOT varchar2(50)  NOT NULL,
    MARMOT varchar2(50)  NOT NULL,
    MODMOT varchar2(50)  NOT NULL,
    COLMOT varchar2(50)  NOT NULL,
    PRECOMMOT number(18,2)  NOT NULL,
    PREVENMOT number(18,2)  NOT NULL,
    GARMOT varchar2(20)  NOT NULL,
    STOCK integer  NOT NULL,
    ESTMOT char(1)  NOT NULL,
    CONSTRAINT MOTOS_pk PRIMARY KEY (IDMOT)
) ;

CREATE TABLE REPUESTOS (
    IDREP integer  NOT NULL,
    NOMREP varchar2(20)  NOT NULL,
    MARREP varchar2(50)  NOT NULL,
    MODREP varchar2(50)  NOT NULL,
    PRECOMREP number(18,2)  NOT NULL,
    PREVENREP number(18,2)  NOT NULL,
    STOCK integer  NOT NULL,
    ESTREP char(1)  NOT NULL,
    CONSTRAINT REPUESTOS_pk PRIMARY KEY (IDREP)
) ;

CREATE TABLE PROVEEDORES (
    IDPRO integer  NOT NULL,
    NOMPRO varchar2(50)  NOT NULL,
    RUCPRO integer  NOT NULL,
    DIRPRO varchar2(50)  NOT NULL,
    PROPRO varchar2(50)  NOT NULL,
    CELPRO char(9)  NOT NULL,
    ESTPRO char(1)  NOT NULL,
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (IDPRO)
) ;

CREATE TABLE COMPRA (
    IDCOM integer  NOT NULL,
    FECCOM date  NOT NULL,
    FOR_PAG varchar2(50) NOT NULL,
    IDEMP integer  NOT NULL,
    IDPRO integer  NOT NULL,
    CONSTRAINT COMPRA_pk PRIMARY KEY (IDCOM)
) ;

CREATE TABLE COMPRA_DETALLE (
    IDCOMDET integer  NOT NULL,
    CANTCOMDET integer  NOT NULL,
    IDREP int  NOT NULL,
    IDMOT int NOT NULL,
    IDCOM int NOT NULL,
    CONSTRAINT COMPRA_DETALLE_pk PRIMARY KEY (IDCOMDET)
) ;

CREATE TABLE VENTA (
    IDVEN integer  NOT NULL,
    FECVEN date  NOT NULL,
    FOR_PAG varchar2(50) NOT NULL,
    IDCLI integer  NOT NULL,
    IDEMP integer  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVEN)
) ;

CREATE TABLE VENTA_DETALLE (
    IDVENDET integer  NOT NULL,
    CANTVENDET integer  NOT NULL,
    IDVENT integer  NOT NULL,
    IDMOT int NOT NULL,
    IDREP int NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENDET)
) ;

CREATE SEQUENCE INC_CLI
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_EMP
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_MOT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_REP
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_PROV
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_VEN
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_VENDET
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_COM
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_COMDET
START WITH 1
INCREMENT BY 1;


CREATE TRIGGER TRG_INC_CLI
  BEFORE INSERT ON CLIENTE 
  FOR EACH ROW
  BEGIN
    SELECT INC_CLI.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
  END;
  /

CREATE TRIGGER TRG_INC_COM
  BEFORE INSERT ON COMPRA
  FOR EACH ROW
  BEGIN
    SELECT INC_COM.NEXTVAL INTO :NEW.IDCOM FROM DUAL;
  END;
  /
  CREATE TRIGGER TRG_INC_COMDET
  BEFORE INSERT ON COMPRA_DETALLE
  FOR EACH ROW
  BEGIN
    SELECT INC_COMDET.NEXTVAL INTO :NEW.IDCOMDET FROM DUAL;
  END;
  /
    CREATE TRIGGER TRG_INC_EMP
  BEFORE INSERT ON EMPLEADO
  FOR EACH ROW
  BEGIN
    SELECT INC_EMP.NEXTVAL INTO :NEW.IDEMP FROM DUAL;
  END;
  /
      CREATE TRIGGER TRG_INC_MOT
  BEFORE INSERT ON MOTOS
  FOR EACH ROW
  BEGIN
    SELECT INC_MOT.NEXTVAL INTO :NEW.IDMOT FROM DUAL;
  END;
  /
        CREATE TRIGGER TRG_INC_REP
  BEFORE INSERT ON REPUESTOS
  FOR EACH ROW
  BEGIN
    SELECT INC_REP.NEXTVAL INTO :NEW.IDREP FROM DUAL;
  END;
  /
        CREATE TRIGGER TRG_INC_PROV
  BEFORE INSERT ON PROVEEDORES
  FOR EACH ROW
  BEGIN
    SELECT INC_PROV.NEXTVAL INTO :NEW.IDPRO FROM DUAL;
  END;
  /
          CREATE TRIGGER TRG_INC_VEN
  BEFORE INSERT ON VENTA
  FOR EACH ROW
  BEGIN
    SELECT INC_VEN.NEXTVAL INTO :NEW.IDVEN FROM DUAL;
  END;
  /
            CREATE TRIGGER TRG_INC_VENDET
  BEFORE INSERT ON VENTA_DETALLE
  FOR EACH ROW
  BEGIN
    SELECT INC_VENDET.NEXTVAL INTO :NEW.IDVENDET FROM DUAL;
  END;
  /
  

  INSERT ALL
       INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Miguel','Gutierrez','78452169','miguel@gmail.com','995687412','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Jose','Sivera','14256985','jose@gmail.com','992666961','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Mario','Quispe','74200697','mario@gmail.com','992693446','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Alberto','Manriquez','54582145','alberto@gmail.com','992857425','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Maria','Aribe','15423514','maria@gmail.com','993797613','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Abel','Sanchez','15426385','abel@gmail.com','992668960','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Antonio','Sánchez','21563100','antonio@gmail.com','910559418','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Maribel','Rodriguez','97582145','maribel@gmail.com','98225631','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Albel','Rodriguez','25468236','albel@gmail.com','993621458','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Marios','Conilla','26854796','marios@gmail.com','994562352','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Aladin','Castro','75866927','aladin@gmail.com','965985459','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Juan','Quispe','77656696','juan@gmail.com','96577418','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Naomi','Manriquez','78466660','naomi@gmail.com','954789455','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Jesus','Carnica','73266960','jesus@gmail.com','965871452','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Carlos','Sanchez','75668960','carlos@gmail.com','967412785','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Mishell','Palomino','79785690','mishell@gmail.com','995612478','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Juana','Malazquez','71266960','juana@gmail.com','974826986','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Adolfo','Manrique','78956412','adolfo@gmail.com','923654178','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Martha','Rodriguez','73456960','martha@gmail.com','969651227','A')
        INTO CLIENTE (NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE)
       VALUES('Adolfo','Meneses','76254960','adolfo@gmail.com','966298785','A')
       SELECT * FROM DUAL
COMMIT;   

 INSERT ALL
       INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES ('Alfonso','Lopez','alfonzo@gmail.com','995687412','05/12/2001','75412368','A','jose','123')
      INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Alber','Sivera','alber@gmail.com','965966459','04/12/2002','99266687','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Alberto','Quispe','alberto@gmail.com','96574148','04/12/2002','99656696','A','jose','123')
    INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Mantos','Manriquez','mantos@gmail.com','954821455','04/12/2002','98466660','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Albino','Aribe','albino@gmail.com','965878554','04/12/2002','99266960','A','jose','123')
       INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Abelino','Sanchez','abelino@gmail.com','967481456','04/12/2002','97668960','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Manuel','Sanchez','manuel@gmail.com','995651485','04/12/2002','99785690','A','jose','123')
       INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Josefino','Rodriguez','josefino@gmail.com','974826145','04/10/2002','91266960','A','jose','123')
     INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Albelia','Rodriguez','albelia@gmail.com','969651445','04/11/2002','99456960','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Mariosa','Conilla','mariosa@gmail.com','965898485','04/12/2002','99254960','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Jose','Sivera','jose@gmail.com','992666961','04/12/2002','14256985','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Mario','Quispe','mario@gmail.com','992693446','04/12/2002','74200697','A','jose','123')
       INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Alberto','Manriquez','alberto@gmail.com','992857425','04/12/2002','54582145','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Maria','Aribe','maria@gmail.com','993797613','04/12/2002','15423514','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Abel','Sanchez','abel@gmail.com','992668960','04/12/2002','15426385','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Antonio','Sanchez','antonio@gmail.com','910559418','04/12/2002','21563100','A','jose','123')
       INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Maribel','Rodriguez','maribel@gmail.com','98225631','04/12/2002','97582145','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Albel','Rodriguez','albel@gmail.com','993621458','04/12/2002','25468236','A','jose','123')
       INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Erick','Velazques','erick@gmail.com','921456387','04/12/2002','71245896','A','jose','123')
        INTO EMPLEADO (NOMEMP,APEEMP,EMAILEMP,CELEMP,FEHCREGEMP,DOCEMP,ESTEMP,USUEMP,PASEMP)
       VALUES('Marios','Conilla','marios@gmail.com','994562352','04/12/2002','26854796','A','jose','123')
       SELECT * FROM DUAL
COMMIT;   

INSERT ALL
       INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Yamaha', 'ML-58741', 'azul', '2 años','60', '12059,00','15000,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Suzuki', 'J-84329', 'verde', '1 años','30', '11450,00','16541,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Yamaha', 'MT-07 2021-2022', 'azul', '2 años','100', '11059,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Suzuki', 'G-85529', 'negro', '1 años','50', '12550,00','17059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Aprilia', 'L-20186', 'azul', '2 años','82', '15789,00','20059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Ducati', 'L-20189', 'Amarillo', '2 años','40', '13859,00','18059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Honda', 'L-20205', 'azul', '2 años','100', '10859,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Cagiva', 'G-85528', 'negro', '1 años','50', '20550,00','22059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Suzuki', 'L-20187', 'azul', '2 años','82', '12789,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Yamaha', 'MT-07 2018-2020', 'Amarillo', '2 años','40', '11859,00','16059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Puma', 'MF-58741', 'azul', '2 años','60', '12059,00','15000,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Generico', 'JF-84329', 'verde', '1 años','30', '11450,00','16541,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Puma', 'MTH-07 2021-2022', 'azul', '2 años','100', '11059,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Torito', 'GH-85529', 'negro', '1 años','50', '12550,00','17059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Puma', 'LQ-20186', 'azul', '2 años','82', '15789,00','20059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Ballay', 'LQ-20189', 'Amarillo', '2 años','40', '13859,00','18059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Honda', 'LT-20205', 'azul', '2 años','100', '10859,00','15059,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Moto Triciclos','Honda', 'GT-85529', 'negro', '1 años','50', '20440,00','22999,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Bicimoto','Suzuki', 'LI-20186', 'azul', '2 años','82', '12889,00','15159,00','A')
        INTO MOTOS (CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, STOCK, PRECOMMOT,PREVENMOT, ESTMOT)
       VALUES('Motocicletas','Yamaha', 'MIT-07 2018-2020', 'Amarillo', '2 años','40', '12059,00','17859,00','A')
        SELECT * FROM DUAL
COMMIT;

INSERT ALL
       INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Llantas','Generico', 'M-2010', '30','40','49', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Medidor de Velocidad','Generico', 'G-2500', '50','181,00','250,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Grips','RockBros', 'BT1802GR', '60','35','55', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Disco de freno','Generico', 'M-2015', '40','91,00','136,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Juego de embrague','Honda', 'Crf50F', '60','150,00','210,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Llantas','Honda', 'M-2020', '52','65','79', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Juego de freno','Generica', 'Crf70g', '68','100,00','110,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Faros','Generico', 'G-E582', '40','340,00','550,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Grips','RockBros', 'BT1001BKBK', '38','28','50', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Aros','RockBros', 'AF-2020', '25','50','80', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Tubo escape','Generico', 'Mr-2010', '30','40','49', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Faro','Generico', 'GS-2500', '50','181,00','250,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Faro','RockBros', 'BRT1802GR', '60','35','55', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Retr','Generico', 'MY-2015', '40','91,00','136,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Juego de embrague','Honda', 'Carf50F', '60','150,00','210,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Llantas','Honda', 'MW-2020', '52','65','79', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Juego de freno','Generica', 'Crdf70g', '68','100,00','110,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Faros','Generico', 'GT-E582', '40','340,00','550,00', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Grips','RockBros', 'BU1001BKBK', '38','28','50', 'A')
        INTO REPUESTOS (NOMREP, MARREP, MODREP, STOCK, PRECOMREP,PREVENREP, ESTREP) 
        VALUES('Aros','RockBros', 'AS-2020', '25','50','80', 'A')
        SELECT * FROM DUAL
COMMIT;

INSERT ALL
       INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Honda Del Peru S.A','20493508645', 'Av. República de Panamá 3545', 'Lima', '968468550','A')
        INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES('Wanxin Internacional S.A.C.','20507553811', 'Av. la Marina 800,', 'Callao', '014630808','A')
        INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('BAJAJ DEL PERU SAC','20548599882', 'Av. Argentina 3250', 'Lima', '978683460','A')
        INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Cayman S.A.C','20380456444', 'Jr. Jimenéz Pimentel 464', 'Callao', '013239010','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Ronco Motor´s S.A.C.','20510421583', 'Av Nicolás Arriola 2278', 'Lima', '971946384','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('ITALIKA STORE EIRL','20542544237', 'Av. Universitaria 65', 'Lima', '950086254','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Tvs Wireless S.A.C','20523361555', 'URB. SANTA CATALINA 262 LA VICTORIA', 'Lima', '995687451','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Socopur S.A.C.','20128967606', 'Av. Separadora Industrial 651', 'Lima', '015122860','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Yamaha Motor del Peru SA','20383929050', 'Av. República de Panamá 4344', 'Lima', '012022100','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Tilgreen SAC','20104085639', 'JR. 7 DE JUNIO NRO. 0007 URB. PICHANAQUI', 'Junin', '985461278','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Reveymo S.A','20493678645', 'Av. República de Panamá 3545', 'Lima', '968468550','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES('Zima Import & Export S.A.C.','20507553711', 'Av. la Marina 800,', 'Callao', '014630808','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES('Scoomart SAC','04538599882', 'Av. Argentina 3250', 'Lima', '978683460','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES('imoveblue S.A.C','89670456448', 'Jr. Jimenéz Pimentel 464', 'Callao', '013239010','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Moto PARADISE  S.A.C.','20587125983', 'Av Nicolás Arriola 2278', 'Lima', '971946384','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Comamon S.A.C','79942944258', 'Av. Universitaria 65', 'Lima', '950086254','A')
        INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Emoveyou S.A.C','80523361985', 'URB. SANTA CATALINA 262 LA VICTORIA', 'Lima', '995687451','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Motos APOLLO S.A.C.','90128267677', 'Av. Separadora Industrial 651', 'Lima', '015122860','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Lemev SA','20143929151', 'Av. República de Panamá 4344', 'Lima', '012022100','A')
         INTO PROVEEDORES (NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
       VALUES ('Pimpamcross SAC','19944038400', 'JR. 7 DE JUNIO NRO. 0007 URB. PICHANAQUI', 'Junin', '985461278','A')
       SELECT * FROM DUAL
COMMIT;  

ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_COMPRA
    FOREIGN KEY (IDCOM)
    REFERENCES COMPRA (IDCOM);

ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_MOTOS
    FOREIGN KEY (IDMOT)
    REFERENCES MOTOS (IDMOT);

ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_REPUESTOS
    FOREIGN KEY (IDREP)
    REFERENCES REPUESTOS (IDREP);

ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_EMPLEADO
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);

ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY (IDPRO)
    REFERENCES PROVEEDORES (IDPRO);

ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);

    ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_MOTOS
    FOREIGN KEY (IDMOT)
    REFERENCES MOTOS (IDMOT);

ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_REPUESTOS
    FOREIGN KEY (IDREP)
    REFERENCES REPUESTOS (IDREP);
    

ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVENT)
    REFERENCES VENTA (IDVEN);

ALTER TABLE VENTA ADD CONSTRAINT VENTA_EMPLEADO
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);
 
INSERT ALL
       INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES ('02/05/22','Efectivo', '2', '2')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('02/05/22','YAPE', '1', '6')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('03/05/22','Efectivo', '4', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('03/05/22','Bin', '5', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('04/05/22','Efectivo', '3', '2')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('04/05/22','YAPE', '4', '6')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('04/05/22','Efectivo', '5', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('05/05/22','Bin', '6', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('05/05/22','Efectivo', '7', '2')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('05/05/22','YAPE', '8', '6')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('06/05/22','Efectivo', '9', '5')
        INTO VENTA (FECVEN, FOR_PAG, IDCLI, IDEMP)
       VALUES('06/05/22','Bin', '11', '5')
       SELECT * FROM DUAL
COMMIT;  

INSERT ALL
       INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES ('02/05/22','Efectivo', '2', '2')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('02/05/22','YAPE', '1', '6')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('03/05/22','Efectivo', '4', '5')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('03/05/22','Bin', '5', '5')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('04/05/22','Efectivo', '3', '2')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('04/05/22','YAPE', '4', '6')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('04/05/22','Efectivo', '5', '5')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('05/05/22','Bin', '6', '5')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('05/05/22','Efectivo', '7', '2')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('05/05/22','YAPE', '8', '6')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('06/05/22','Efectivo', '9', '5')
        INTO COMPRA (FECCOM, FOR_PAG, IDPRO, IDEMP)
       VALUES('06/05/22','Bin', '11', '5')
       SELECT * FROM DUAL
COMMIT;

INSERT ALL
       INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('2','1', '10', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','2', '11', '3')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','3', '12', '4')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','4', '13', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('2','5', '14', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','6', '15', '3')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','7', '16', '4')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','8', '9', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('2','9', '17', '2')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','10', '18', '3')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','11', '19', '4')
        INTO VENTA_DETALLE(CANTVENDET, IDVENT, IDMOT, IDREP) 
        VALUES('1','12', '20', '2')
       SELECT * FROM DUAL
COMMIT;  
  

INSERT ALL
       INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('2','3', '10', '2')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','4', '11', '3')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','1', '12', '4')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','3', '13', '2')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('2','3', '14', '2')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','4', '15', '3')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','1', '16', '4')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','3', '9', '2')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('2','3', '17', '2')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','4', '18', '3')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','1', '19', '4')
        INTO COMPRA_DETALLE (CANTCOMDET, IDCOM, IDMOT, IDREP) 
        VALUES('1','3', '20', '2')
       SELECT * FROM DUAL
COMMIT;  


--------------------------------------------------------------------------------Procedure CLIENTE -------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE spInsertCliente
	(
		NOMCLIE VARCHAR2,
		APECLIE varchar2,
        DOCCLIE char,
		EMACLIE varchar2,
		CELCLIE char,
		ESTCLIE char
			)
AS
BEGIN
        INSERT INTO CLIENTE
			(NOMCLIE, APECLIE, DOCCLIE, EMACLIE, CELCLIE, ESTCLIE)
        VALUES  
        (UPPER(NOMCLIE), UPPER(APECLIE),DOCCLIE, EMACLIE, CELCLIE , ESTCLIE);
END;
/

    --ACTUALIZACION DE DATOS EN CLIENTE
    CREATE OR REPLACE PROCEDURE spUpdateCliente
    (
            IDC  INT,
            NOMCLIENTE VARCHAR2,
            APECLIENTE varchar2,
            DNI char,
            EMAIL varchar2,
            CELULAR char,
            ESTADOCLIENTE char
            
            
    )
    AS
    BEGIN
        UPDATE CLIENTE SET NOMCLIE=UPPER(NOMCLIENTE), APECLIE=UPPER(APECLIENTE),DOCCLIE=DNI,EMACLIE=EMAIL,CELCLIE=CELULAR,ESTCLIE=ESTADOCLIENTE where IDCLI= IDC;
    END;
/
--PROCEDURE DE ELIMINAR PERSONA
CREATE OR REPLACE PROCEDURE spEliminarCliente
    (
    IDCLIE int
    )
AS
BEGIN
    UPDATE CLIENTE SET ESTCLIE='I' WHERE IDCLI = IDCLIE;
END;
/

--PROCEDURE DE HABILITAR PERSONA
CREATE OR REPLACE PROCEDURE spHabilitarPersona
    (
    IDCLIE int
    )
AS
BEGIN
    UPDATE CLIENTE SET ESTCLIE ='A' WHERE IDCLI = IDCLIE;
END;
/

--------------------------------------------------------------------------------Procedure EMPLEADO -------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE spInsertEMPLEADO
	(
		NOMEMP VARCHAR2,
		APEEMP varchar2,  
		EMAILEMP varchar2,
        CELEMP char,
        FEHCREGEMP date,
        DOCEMP char,	
		ESTEMP char,
        USUEMP VARCHAR2,
        PASEMP VARCHAR2
			)
AS
BEGIN
        INSERT INTO empleado
			(NOMEMP, APEEMP, EMAILEMP, CELEMP, FEHCREGEMP, DOCEMP, ESTEMP, USUEMP ,PASEMP)
        VALUES  
        (UPPER(NOMEMP), UPPER(APEEMP),EMAILEMP, CELEMP, FEHCREGEMP, DOCEMP , ESTEMP ,USUEMP ,PASEMP);
END;
/

    --ACTUALIZACION DE DATOS EN EMPLEADO
    CREATE OR REPLACE PROCEDURE spUpdateEMPLEADO
    (
         
            NOMEMPLEADO VARCHAR2,
            APEEMPLEADO varchar2,
            EMAIL varchar2,
            CELULAR char,
            FECHA date,        
            DNI char,
            ESTEMPLEADO char,
            USUARIO VARCHAR2,
            CONTRASEÑA VARCHAR2,
            IDP  INT
           
            
    )
    AS
    BEGIN
        UPDATE empleado SET NOMEMP=UPPER(NOMEMPLEADO), APEEMP=UPPER(APEEMPLEADO),EMAILEMP=EMAIL,CELEMP=CELULAR,FEHCREGEMP=FECHA,DOCEMP=DNI,ESTEMP=ESTEMPLEADO, USUEMP=USUARIO, PASEMP=CONTRASEÑA where IDEMP= IDP;
    END;
    /
    
    --PROCEDURE DE ELIMINAR EMPLEADO
CREATE OR REPLACE PROCEDURE spEliminarEMPLEADO
    (
    IDEMPL int
    )
AS
BEGIN
    UPDATE empleado SET ESTEMP='I' WHERE IDEMPL = IDEMP;
END;
/

--PROCEDURE DE RESTAURAR EMPLEADO
CREATE OR REPLACE PROCEDURE spHabilitarEMPLEADO
    (
    IDEMPL int
    )
AS
BEGIN
    UPDATE EMPLEADO SET ESTEMP ='A' WHERE IDEMP = IDEMPL;
END;
/
--------------------------------------------------------------------------------Procedure MOTOS -------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE spInsertMOTOS
	(
		CATMOT VARCHAR2,
		MARMOT varchar2,  
		MODMOT varchar2,
        COLMOT varchar2,
        GARMOT varchar2,
        PRECOMMOT number,	
		PREVENMOT number,
        STOCK INT,
        ESTMOT char
			)
AS
BEGIN
        INSERT INTO MOTOS
			(CATMOT, MARMOT, MODMOT, COLMOT, GARMOT, PRECOMMOT, PREVENMOT, STOCK, ESTMOT)
        VALUES  
        (UPPER(CATMOT), UPPER(MARMOT),UPPER(MODMOT), UPPER(COLMOT), UPPER(GARMOT), PRECOMMOT , PREVENMOT, STOCK,ESTMOT);
END;

/

    --ACTUALIZACION DE DATOS EN MOTOS
    CREATE OR REPLACE PROCEDURE spUpdateMOTOS
    (        
        CATMOTOS VARCHAR2,
		MARMOTOS varchar2,  
		MODMOTOS varchar2,
        COLMOTOS varchar2,
        GARMOTOS varchar2,
        PRECOMMOTOS number,	
		PREVENMOTOS number,
        STOCKMOT INT,
        ESTMOTOS char,
        IDM INT
                  
    )
    AS
    BEGIN
        UPDATE MOTOS SET CATMOT=UPPER(CATMOTOS), MARMOT=UPPER(MARMOTOS), MODMOT= UPPER(MODMOTOS), COLMOT= UPPER(COLMOTOS), GARMOT= UPPER(GARMOTOS), PRECOMMOT=PRECOMMOTOS, PREVENMOT=PREVENMOTOS, STOCK=STOCKMOT, ESTMOT=ESTMOTOS where IDMOT= IDM;
    END;
    /
    --PROCEDURE DE ELIMINAR MOTOS
CREATE OR REPLACE PROCEDURE spEliminarMOTOS
    (
    IDEMOT int
    )
AS
BEGIN
    UPDATE MOTOS SET ESTMOT='I' WHERE IDMOT = IDMOT;
END;
/

--PROCEDURE DE RESTAURAR motos
CREATE OR REPLACE PROCEDURE spHabilitarMOTOS
    (
    IDMO int
    )
AS
BEGIN
    UPDATE MOTOS SET ESTMOT ='A' WHERE IDMOT = IDMO;
END;
/

--------------------------------------------------------------------------------Procedure proveedores -------------------------------------------------------------------------------------------


CREATE OR REPLACE PROCEDURE spInsertPROVEEDORES
	(
    NOMPRO varchar2,
    RUCPRO integer,
    DIRPRO varchar2,
    PROPRO varchar2,
    CELPRO char,
    ESTPRO char
			)
AS
BEGIN
        INSERT INTO PROVEEDORES
			(NOMPRO, RUCPRO, DIRPRO, PROPRO, CELPRO, ESTPRO)
        VALUES  
        (UPPER(NOMPRO), RUCPRO ,DIRPRO, PROPRO, CELPRO, ESTPRO);
END;
/

--ACTUALIZACION DE DATOS EN PROVEEDORES
    CREATE OR REPLACE PROCEDURE spUpdatPROVEEDORES
    (        
    NOMPROOVE varchar2,
    RUCPROOVE integer,
    DIRPROOVE varchar2,
    PROPROOVE varchar2,
    CELPROOVE char,
    ESTPROOVE char,
    IDPROOVE INT
                  
    )
    AS
    BEGIN
        UPDATE PROVEEDORES SET NOMPRO =UPPER(NOMPROOVE), RUCPRO  = RUCPROOVE, DIRPRO = UPPER(DIRPROOVE), PROPRO = UPPER(PROPROOVE), CELPRO = ESTPROOVE where IDPRO = IDPROOVE;
    END;
    /
    
    
    --PROCEDURE DE ELIMINAR PROVEEDORES
CREATE OR REPLACE PROCEDURE spEliminarPROVEEDORES
    (
    IDPROOVE int
    )
AS
BEGIN
    UPDATE PROVEEDORES SET ESTPRO='I' WHERE IDPRO  = IDPROOVE;
END;
/

--PROCEDURE DE RESTAURAR PROVEEDORES
CREATE OR REPLACE PROCEDURE spHabilitarPROVEEDORES
    (
    IDPROO int
    )
AS
BEGIN
    UPDATE PROVEEDORES SET ESTPRO ='A' WHERE IDPRO = IDPROO;
END;
/

---------------------------------------------------------------------------------PROCEDURE DE VENTA-----------------------------------------------------------------------------------

--PROCEDURE DE VENTA
CREATE OR REPLACE PROCEDURE spRegistrarVenta
    (
    FECHA DATE,
    PAGO CHAR,
    CLIENTE INT,
    EMPLEADO INT
    )
AS

BEGIN

    INSERT INTO VENTA 
    (FECVEN,FOR_PAG,IDCLI,IDEMP) 
    VALUES 
    (FECHA,PAGO,CLIENTE,EMPLEADO);
    
END;
/

CREATE OR REPLACE PROCEDURE spRegistrarVentaDetalle
    (
     CANTIDAD INT,
    IDVENTA INT,
    IDMOTO INT,
    IDREPUESTO INT
    ) 
AS
BEGIN

    INSERT INTO VENTA_DETALLE
    (CANTVENDET,IDVENT,IDMOT,IDREP)
    VALUES 
    (CANTIDAD,IDVENTA,IDMOTO,IDREPUESTO);
    
    
END;
/

---------------------------------------------------------------------------------vista DE VENTA-----------------------------------------------------------------------------------

CREATE VIEW vVenta
AS
SELECT
V.FOR_PAG,
mo.catmot || ' '||mo.modmot || ' '||mo.marmot AS moto,
mo.prevenmot,
mo.prevenmot * VD.CANTVENDET as importe,
C.nomclie || ' ' || C.apeclie AS NOMBRES,
c.docclie,
VD.CANTVENDET,
VD.IDVENT
FROM
VENTA  V JOIN VENTA_DETALLE  VD
ON V.IDVEN=VD.IDVENT JOIN cliente C ON V.IDCLI= C.IDCLI JOIN motos MO on vd.idmot = mo.idmot
;

CREATE OR REPLACE VIEW ProductoTop AS
SELECT mot.marmot, SUM(VDT.CANTVENDET) AS Cantidad FROM VENTA_DETALLE VDT
INNER JOIN motos mot
ON VDT.IDMOT = mot.IDMOT
GROUP BY mot.marmot
ORDER BY Cantidad DESC ;
/

SELECT * FROM ProductoTop WHERE rownum <=5;